{
    "port": 80, 
    # "port": 8000,
    "server_name": "potato annotator",
    "annotation_task_name": "Economic Article Quant Annotation",
    "output_annotation_dir": "annotation_output/collection3-2/",
    "output_annotation_format": "csv",
    "annotation_codebook_url": "https://www.dropbox.com/scl/fi/lqdluyacpaksl4mbyjuk5/Quant-Codebook.pdf?rlkey=xy7h3ry9cd7su8kphzanwrjx0&dl=0",
    "data_files": [
        "data_files/quants3-2.csv"
    ],
    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },
    "list_as_text": {
        "text_list_prefix_type": "None",
        "horizontal": true
    },
    "user_config": {
        "allow_all_users": true,
        "users": []
    },
    "login": {
        "type": "url_direct",
        "url_argument": "PROLIFIC_PID"
    },
    "jumping_to_id_disabled": false,
    "hide_navbar": true,
    "surveyflow": {
        "on": true,
        "order": [
            "pre_annotation", 
            "post_annotation"
        ],
        "pre_annotation": [
            "surveyflow/intro.jsonl",
            "surveyflow/instructions0.jsonl",
            "surveyflow/instructions1.jsonl",
            "surveyflow/instructions1_example.jsonl",
            "surveyflow/instructions2.jsonl",
            "surveyflow/instructions2_example.jsonl",
            "surveyflow/instructions3.jsonl",
            "surveyflow/instructions3_example.jsonl",
            "surveyflow/instructions_confirm.jsonl",
            "surveyflow/example1.jsonl",
            "surveyflow/example2.jsonl",
            "surveyflow/confirm.jsonl"
        ], 
        "post_annotation": [
            "surveyflow/end.jsonl"
        ]
    },
    "automatic_assignment": {
        "on": true,
        "output_filename": "task_assignment.json",
        "sampling_strategy": "random",
        "labels_per_instance": 20,
        "instance_per_annotator": 50,
        "test_question_per_annotator": 0,
        "users": []
    },
    "alert_time_each_instance": 10000000,
    "annotation_schemes": [
            {
                "annotation_type": "radio",
                "name": "frame",
                "description": "Question 1: The highlighted quantity should have a general type. Please label the type, or select 'None of the above' is a date or otherwise not relevant to the U.S. economy",
                "labels": [
                    
                    {
                        "name": "Macroeconomic / General Economic Conditions (e.g., discusses jobs, housing prices, and oil prices)",
                        "tooltip": "",
                        "key_value": "0"
                    },
                    {
                        "name": "Firm-specific (e.g., discusses stock prices, debt offerings, and capital investments)",
                        "tooltip": "",
                        "key_value": "1"
                    },
                    {
                        "name": "Industry-specific (e.g., discusses agricultural prices, manufacturing output, and retail sales)",
                        "tooltip": "",
                        "key_value": "2"
                    },
                    {
                        "name": "Government revenue and expenses (e.g., discusses taxes, budgets, and treasury issuances)",
                        "tooltip": "",
                        "key_value": "3"
                    },
                    {
                        "name": "Personal (e.g., discusses household expenditures and personal debts)",
                        "tooltip": "",
                        "key_value": "4"
                    },
                    {
                        "name": "Other",
                        "tooltip": "",
                        "key_value": "5"
                    },
                    {
                        "name": "Not Relevant to the U.S. Economy",
                        "tooltip": "",
                        "key_value": "6"
                    },
                ],
                "displaying_score": true,
                "label_requirement": {
                    "required": true
                }
            },
            {
                "annotation_type": "radio",
                "name": "macro_indicator",
                "description": "Question 2: If the quantity's general type is 'Macroeconomic / General Economic Conditions', please label the specific macroeconomic indicator. Select 'None of the above' if the quantity is not relevant to the U.S. economy or is not a macroeconomic / general conditions type.",
                "labels": [
                {
                    "name": "Job Numbers (e.g., jobs, unemployment)",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "Market Numbers (e.g., any financial market)",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Housing (e.g., Start, Sales, Pricing)",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "Macroeconomy (e.g., GDP)",
                    "tooltip": "",
                    "key_value": "3"
                },
                {
                    "name": "Wages (e.g., minimum wage, average wage)",
                    "tooltip": "",
                    "key_value": "4"
                },
                {
                    "name": "Prices (e.g., CPI, PPI)",
                    "tooltip": "",
                    "key_value": "5"
                },
                {
                    "name": "Confidence",
                    "tooltip": "",
                    "key_value": "6"
                },
                {
                    "name": "Retail Sales",
                    "tooltip": "",
                    "key_value": "7"
                },
                {
                    "name": "Interest Rates (e.g., Fed, Mortgage)",
                    "tooltip": "",
                    "key_value": "8"
                },
                {
                    "name": "Currency Values",
                    "tooltip": "",
                    "key_value": "9"
                },
                {
                    "name": "Energy Prices (eg., oil, gas)",
                    "tooltip": "",
                    "key_value": "10"
                },
                {
                    "name": "Other",
                    "tooltip": "",
                    "key_value": "11"
                },
                {
                    "name": "Not general type 'Macroeconomic / General Economic Conditions'",
                    "tooltip": "",
                    "key_value": "12"
                },
                {
                    "name": "Not Relevant to the U.S. Economy",
                    "tooltip": "",
                    "key_value": "13"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        {
                "annotation_type": "radio",
                "name": "spin",
                "description": "Question 3: If the quantity's general type is 'Macroeconomic / General Economic Conditions', what spin does the writer of the excerpt put on the highlighted quantity?",
                "labels": [
                {
                    "name": "Positive (e.g., inflation dropped)",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "Negative (e.g., prices skyrocketed)",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Neutral (e.g., GDP was worth X US dollars)",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "Unknown",
                    "tooltip": "cannot tell",
                    "key_value": "3"
                },   
                {
                    "name": "Not general type 'Macroeconomic / General Economic Conditions'",
                    "tooltip": "",
                    "key_value": "4"
                },
                {
                    "name": "Not Relevant to the U.S. Economy",
                    "tooltip": "",
                    "key_value": "5"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        }
    ],
    "html_layout": "templates/layout.html",

    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}