{
    "port": 8000,
    "server_name": "potato annotator",
    "annotation_task_name": "Economic Article Annotation",
    "output_annotation_dir": "annotation_output/pilot/",
    "output_annotation_format": "tsv",
    "annotation_codebook_url": "",
    "data_files": [
        "data_files/articles.csv"
    ],
    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },
    "list_as_text": {
        "text_list_prefix_type": "None",
        "horizontal": true
    },
    "user_config": {
        "allow_all_users": true,
        "users": []
    },
    "login": {
        "type": "url_direct",
        "url_argument": "PROLIFIC_PID"
    },
    "jumping_to_id_disabled": false,
    "hide_navbar": true,
    "surveyflow": {
        "on": true,
        "order": [
            "pre_annotation",
            "post_annotation"
        ],
        "pre_annotation": [
            "surveyflow/intro.jsonl",
            "surveyflow/1_Completely_different.jsonl",
            "surveyflow/2_Mostly_different.jsonl",
            "surveyflow/3_Somewhat_similar.jsonl",
            "surveyflow/4_Mostly_the_same.jsonl",
            "surveyflow/5_Completely_the_same.jsonl",
            "surveyflow/consent.jsonl",
            "surveyflow/instruction.jsonl"
        ],
        "prestudy_passed": [
            "surveyflow/prestudy_pass.jsonl"
        ],
        "prestudy_failed": [
            "surveyflow/prestudy_fail.jsonl"
        ],
        "post_annotation": [
            "surveyflow/experience.jsonl",
            "surveyflow/end.jsonl"
        ],
        "testing": [
            "surveyflow/testing.jsonl"
        ]
    },
    "prestudy": {
        "on": false,
        "minimum_score": 0.8,
        "groundtruth_key": "whether_match",
        "question_key": "Whether the presented sentences are discussing the same scientific finding",
        "answer_mapping": {
            "Yes": true,
            "No": false
        },
        "pass_page": "surveyflow/prestudy_pass.jsonl",
        "fail_page": "surveyflow/prestudy_fail.jsonl"
    },
    "automatic_assignment": {
        "on": true,
        "output_filename": "task_assignment.json",
        "sampling_strategy": "random",
        "labels_per_instance": 3,
        "instance_per_annotator": 5,
        "test_question_per_annotator": 0,
        "users": []
    },
    "alert_time_each_instance": 10000000,
    "annotation_schemes": [
        {
            "annotation_type": "radio",
            "name": "Economic Conditions",
            "description": "How does this article rate economic conditions in the US?",
            "labels": [
                {
                    "name": "Excellent",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Good",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "Fair",
                    "tooltip": "",
                    "key_value": "3"
                },
                {
                    "name": "Poor",
                    "tooltip": "",
                    "key_value": "4"
                },
                {
                    "name": "No Opinion",
                    "tooltip": "",
                    "key_value": "5"
                },
                {
                    "name": "Not relevant to the US economy",
                    "tooltip": "",
                    "key_value": "6"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        {
            "annotation_type": "radio",
            "name": "Economic Conditions",
            "description": "How does this article rate economic conditions in the US?",
            "labels": [
                {
                    "name": "Excellent",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Good",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "Fair",
                    "tooltip": "",
                    "key_value": "3"
                },
                {
                    "name": "Poor",
                    "tooltip": "",
                    "key_value": "4"
                },
                {
                    "name": "No Opinion",
                    "tooltip": "",
                    "key_value": "5"
                },
                {
                    "name": "Not relevant to the US economy",
                    "tooltip": "",
                    "key_value": "6"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        {
            "annotation_type": "radio",
            "name": "Economic Direction",
            "description": "Does this article state/imply that economic conditions in the US as a whole are. . . ?",
            "labels": [
                {
                    "name": "Getting better",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Getting worse",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "No opinion",
                    "tooltip": "",
                    "key_value": "3"
                },
                {
                    "name": "Not relevant to the US economy",
                    "tooltip": "",
                    "key_value": "4"},
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        }
    ],
    "html_layout": "templates/layout.html",
    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}