{
    # "port": 8000,
    "port": 80,
    "server_name": "potato annotator",
    "annotation_task_name": "Economic Article Annotation",
    "output_annotation_dir": "annotation_output/collection7/",
    "output_annotation_format": "csv",
    "annotation_codebook_url": "https://www.dropbox.com/scl/fi/4bpa4eawf4l2wcisl636p/Article-Codebook.pdf?rlkey=p5j0wjjbjjrhaey1o7t3zjdv1&dl=0",
    "data_files": [
        "data_files/articles7.csv"
    ],
    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },
    "list_as_text": {
        "text_list_prefix_type": "None",
        "horizontal": true
    },
    "user_config": {
        "allow_all_users": true,
        "users": []
    },
    "login": {
        "type": "url_direct",
        "url_argument": "PROLIFIC_PID"
    },
    "jumping_to_id_disabled": false,
    "hide_navbar": true,
    "surveyflow": {
        "on": true,
        "order": [
            "pre_annotation", 
            "post_annotation"
        ],
        "pre_annotation": [
            "surveyflow/intro.jsonl",
            "surveyflow/instructions0.jsonl",
            "surveyflow/instructions1.jsonl",
            "surveyflow/instructions1_example.jsonl",
            "surveyflow/instructions2.jsonl",
            "surveyflow/instructions2_example.jsonl",
            "surveyflow/instructions3.jsonl",
            "surveyflow/instructions3_example.jsonl",
            "surveyflow/instructions_confirm.jsonl",
            "surveyflow/example1.jsonl",
            "surveyflow/example2.jsonl",
            "surveyflow/confirm.jsonl"

        ], 
        "post_annotation": [
            "surveyflow/end.jsonl"
        ]
    },
    "automatic_assignment": {
        "on": true,
        "output_filename": "task_assignment.json",
        "sampling_strategy": "random",
        "labels_per_instance": 30,
        "instance_per_annotator": 25,
        "test_question_per_annotator": 0,
        "users": []
    },
    "alert_time_each_instance": 10000000,
    "annotation_schemes": [
        {
            "annotation_type": "radio",
            "name": "frame",
            "description": "If the article is relevant to the <u>U.S. economy</u> what is the main type of economic information covered in this article?",
            "labels": [
                {
                    "name": "Macroeconomic / General Economic Conditions [in the U.S.]",
                    "tooltip": "e.g., discusses jobs, housing prices, and oil prices",
                    "key_value": "0"
                },
                {
                    "name": "Firm-specific [articles focused on a single business]",
                    "tooltip": "e.g., discusses a firm's stock prices, debt offerings, and capital investments",
                    "key_value": "1"
                },
                {
                    "name": "Industry-specific [articles focused on multiple/all businesses within a single sector e.g. the steel industry]",
                    "tooltip": "e.g., discusses agricultural prices, manufacturing output, and retail sales",
                    "key_value": "2"
                },
                {
                    "name": "Government revenue and expenses [articles focused on lawmaking and government action including treaties, regulation, taxes, laws, and spending]",
                    "tooltip": "e.g., discusses taxes, budgets, and treasury issuances",
                    "key_value": "3"
                },
                {
                    "name": "Personal [articles focused on an individual or small group of individuals]",
                    "tooltip": "e.g., discusses household expenditures and personal debts",
                    "key_value": "4"
                },
                {
                    "name": "Other [articles that do not fit into any of the above categories but are relevant to the U.S. economy]",
                    "tooltip": "",
                    "key_value": "5"
                },
                {
                    "name": "Not Relevant to the U.S. Economy",
                    "tooltip": "",
                    "key_value": "6"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
       
        {
            "annotation_type": "radio",
            "name": "Economic Conditions",
            "description": "If this article is relevant to <u>Macro-economic / General Economic Conditions [in the U.S.]</u>, how does it rate economic conditions in the U.S.?",
            "labels": [
                {
                    "name": "Good",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "Poor",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "No Opinion",
                    "tooltip": "the article does not express an opinion on the state of the economy",
                    "key_value": "2"
                },
                {
                    "name": "Not relevant to the U.S. macroeconomic / general economic conditions",
                    "tooltip": "",
                    "key_value": "3"
                },
                {
                    "name": "Not relevant to the U.S. economy",
                    "tooltip": "",
                    "key_value": "4"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        {
            "annotation_type": "radio",
            "name": "Economic Direction",
            "description": "If this article pertains to <u>Macro-economic / General Economic Conditions [in the U.S.]</u>, does it state/imply that economic conditions in the U.S. as a whole are. . . ?",
            "labels": [
                {
                    "name": "Getting better",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "Getting worse",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Same",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "No opinion",
                    "tooltip": "the article does not express an opinion on the direction of the economy",
                    "key_value": "3"
                },
                {
                    "name": "Not relevant to the U.S. macroeconomic / general economic conditions",
                    "tooltip": "",
                    "key_value": "4"
                },
                {
                    "name": "Not relevant to the U.S. economy",
                    "tooltip": "",
                    "key_value": "5"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        
    ],
    "html_layout": "templates/layout.html",

    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}