{
    "port": 8000,
    "server_name": "potato annotator",
    "annotation_task_name": "Economic Article Annotation",
    "output_annotation_dir": "annotation_output/pilot/",
    "output_annotation_format": "csv",
    "annotation_codebook_url": "https://www.dropbox.com/scl/fi/4bpa4eawf4l2wcisl636p/Article-Codebook.pdf?rlkey=p5j0wjjbjjrhaey1o7t3zjdv1&dl=0",
    "data_files": [
        "data_files/articles.csv"
    ],
    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },
    "list_as_text": {
        "text_list_prefix_type": "None",
        "horizontal": true
    },
    "user_config": {
        "allow_all_users": true,
        "users": []
    },
    "login": {
        "type": "url_direct",
        "url_argument": "PROLIFIC_PID"
    },
    "jumping_to_id_disabled": false,
    "hide_navbar": true,
    "surveyflow": {
        "on": true,
        "order": [
            "pre_annotation", 
            "post_annotation"
        ],
        "pre_annotation": [
            "surveyflow/intro.jsonl",
            "surveyflow/instructions.jsonl"
        ], 
        "post_annotation": [
            "surveyflow/end.jsonl"
        ]
    },
    "automatic_assignment": {
        "on": true,
        "output_filename": "task_assignment.json",
        "sampling_strategy": "random",
        "labels_per_instance": 3,
        "instance_per_annotator": 25,
        "test_question_per_annotator": 0,
        "users": []
    },
    "alert_time_each_instance": 10000000,
    "annotation_schemes": [
        {
            "annotation_type": "radio",
            "name": "relevant",
            "description": "Is this article relevant to the U.S. economy?",
            "labels": [
                {
                    "name": "Yes",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "No",
                    "tooltip": "",
                    "key_value": "1"
                }
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        {
            "annotation_type": "radio",
            "name": "frame",
            "description": "If yes, what is the main type of economic information covered in this article?",
            "labels": [
                {
                    "name": "Macroeconomic / General Economic Conditions",
                    "tooltip": "e.g., discusses jobs, housing prices, and oil prices",
                    "key_value": "0"
                },
                {
                    "name": "Firm-specific",
                    "tooltip": "e.g., discusses stock prices, debt offerings, and capital investments",
                    "key_value": "1"
                },
                {
                    "name": "Industry-specific",
                    "tooltip": "e.g., discusses agricultural prices, manufacturing output, and retail sales",
                    "key_value": "2"
                },
                {
                    "name": "Government revenue and expenses",
                    "tooltip": "e.g., discusses taxes, budgets, and treasury issuances",
                    "key_value": "3"
                },
                {
                    "name": "Personal",
                    "tooltip": "e.g., discusses household expenditures and personal debts",
                    "key_value": "4"
                },
                {
                    "name": "Other",
                    "tooltip": "",
                    "key_value": "5"
                },
                {
                    "name": "Not Relevant to the U.S. Economy",
                    "tooltip": "",
                    "key_value": "6"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
       
        {
            "annotation_type": "radio",
            "name": "Economic Conditions",
            "description": "If this article pertains to Macro-economic / General Economic Conditions, how does it rate economic conditions in the US?",
            "labels": [
                {
                    "name": "Good",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "Poor",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "No Opinion",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "Not relevant to the US economy",
                    "tooltip": "",
                    "key_value": "3"
                },
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        {
            "annotation_type": "radio",
            "name": "Economic Direction",
            "description": "If this article pertains to Macro-economic / General Economic Conditions, does it state/imply that economic conditions in the US as a whole are. . . ?",
            "labels": [
                {
                    "name": "Getting better",
                    "tooltip": "",
                    "key_value": "0"
                },
                {
                    "name": "Getting worse",
                    "tooltip": "",
                    "key_value": "1"
                },
                {
                    "name": "Same",
                    "tooltip": "",
                    "key_value": "2"
                },
                {
                    "name": "No opinion",
                    "tooltip": "",
                    "key_value": "3"
                },
                {
                    "name": "Not relevant to the US economy",
                    "tooltip": "",
                    "key_value": "4"},
            ],
            "displaying_score": true,
            "label_requirement": {
                "required": true
            }
        },
        
    ],
    "html_layout": "templates/layout.html",

    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}